stream_over_http_enabled: true
server:
  http_listen_port: 3200
  log_level: warn
live_store:
  max_live_traces_bytes: 16777216
  max_block_bytes: 4194304
  complete_block_concurrency: 1
  query_block_concurrency: 1
querier:
  max_concurrent_queries: 2
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
storage:
  trace:
    backend: local
    wal:
      path: /var/tempo/wal
    local:
      path: /var/tempo/blocks
usage_report:
  reporting_enabled: false
