definitions.import_backend = local_filesystem
definitions.local.path = /etc/rabbitmq/definitions.json
disk_free_limit.absolute = 512MB
vm_memory_high_watermark.absolute = 256MB
log.console = true
log.console.level = warning
collect_statistics_interval = 10000
max_message_size = 65536
