import { useCallback, useEffect, useRef, useState } from 'react';
import { get, identity, sitePath } from './api';
import type { Order, OrderPage, Equipment, Task, Command } from './api';
type View = 'overview' | 'orders' | 'equipment';
const names: Record<View, string> = { overview: 'Overview', orders: 'Orders', equipment: 'Equipment' };
const currentView = (): View => { const candidate = new URLSearchParams(location.search).get('view'); return candidate && Object.hasOwn(names, candidate) ? candidate as View : 'overview'; };
const label = (value: string) => value.replaceAll('_', ' ').replaceAll('-', ' ').toLowerCase().replace(/^./, x => x.toUpperCase());
const date = (value?: string | null) => value ? new Date(value).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'medium' }) : '—';
const short = (value: string) => value.slice(0, 8);
const terminal = (state: string) => ['COMPLETED', 'COMPLETED_WITH_SHORTAGE', 'SHORTAGE', 'CANCELLED'].includes(state);
function Icon({ kind, size = 20 }: { kind: string; size?: number }) {
  const paths: Record<string, string> = { overview: 'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z', orders: 'M7 3h10v3H7z M5 5H3v16h18V5h-2 M7 11h10 M7 16h7', equipment: 'M3 17h18 M5 17V8h14v9 M8 8V3h8v5 M7 21h1 M16 21h1', refresh: 'M20 7a9 9 0 1 0 1 8 M20 2v6h-6', arrow: 'M4 12h16 M14 6l6 6-6 6', close: 'M5 5l14 14 M19 5L5 19', logout: 'M10 3H3v18h7 M8 12h13 M16 7l5 5-5 5', check: 'M5 12l4 4L19 6', clock: 'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M12 7v5l3 2' };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[kind] ?? paths.overview}/></svg>;
}
function Brand() { return <div className="brand"><svg viewBox="0 0 36 36" aria-hidden="true"><path d="M6 8h24v6H12v8h18v6H6z" fill="currentColor"/><path d="M19 16h11v4H19z" fill="#d9bf76"/></svg><span>Cutover<small>OPERATIONS</small></span></div>; }
function Status({ value }: { value: string }) { return <span className={`status ${['COMPLETED', 'READY', 'ACTIVE'].includes(value) ? 'good' : ['RECONCILIATION_REQUIRED', 'QUARANTINED', 'OUTCOME_UNKNOWN', 'SHORTAGE'].includes(value) ? 'attention' : 'neutral'}`}><i/>{label(value)}</span>; }
export function App({ identityError }: { identityError?: string }) {
  const [view, setView] = useState<View>(currentView);
  const sites = (identity.tokenParsed?.sites as string[] | undefined) ?? [];
  const [site, setSite] = useState(sites[0] ?? 'site-a');
  const [orders, setOrders] = useState<OrderPage>(); const [equipment, setEquipment] = useState<Equipment>(); const [tasks, setTasks] = useState<Task[]>([]);
  const [error, setError] = useState<string>(); const [loading, setLoading] = useState(false); const [observedAt, setObservedAt] = useState<string>();
  const [cursor, setCursor] = useState<string>(); const [selected, setSelected] = useState<Order>(); const [command, setCommand] = useState<Command>(); const [commandError, setCommandError] = useState<string>();
  const dialog = useRef<HTMLDialogElement>(null); const busy = useRef(new Set<string>());
  const requestKey = `${site}:${cursor ?? ''}`; const activeRequest = useRef(requestKey); activeRequest.current = requestKey;
  const refresh = useCallback(async () => {
    if (!identity.authenticated || busy.current.has(requestKey)) return false;
    busy.current.add(requestKey); setLoading(true);
    try {
      const prefix = sitePath(site);
      const results = await Promise.allSettled([get<OrderPage>(`${prefix}/orders?limit=25${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ''}`), get<Equipment>(`${prefix}/equipment`), get<Task[]>(`${prefix}/tasks`)]);
      if (activeRequest.current !== requestKey) return false;
      if (results[0].status === 'fulfilled') setOrders(results[0].value);
      if (results[1].status === 'fulfilled') setEquipment(results[1].value);
      if (results[2].status === 'fulfilled') setTasks(results[2].value);
      const failed = results.find(result => result.status === 'rejected');
      if (failed?.status === 'rejected') throw failed.reason;
      setObservedAt(new Date().toISOString()); setError(undefined); return true;
    } catch (failure) { if (activeRequest.current === requestKey) setError(failure instanceof Error ? failure.message : 'The site is temporarily unavailable.'); return false; }
    finally { busy.current.delete(requestKey); if (activeRequest.current === requestKey) setLoading(false); }
  }, [site, cursor, requestKey]);
  useEffect(() => {
    let cancelled = false; let timer: ReturnType<typeof setTimeout>; let backoff = 5000;
    const poll = async () => { const ok = await refresh(); if (cancelled) return; backoff = ok ? 5000 : Math.min(backoff * 2, 30000); timer = setTimeout(poll, backoff); };
    void poll(); return () => { cancelled = true; clearTimeout(timer); };
  }, [refresh]);
  useEffect(() => { if (selected && !dialog.current?.open) dialog.current?.showModal(); }, [selected]);
  useEffect(() => { const onPop = () => setView(currentView()); addEventListener('popstate', onPop); return () => removeEventListener('popstate', onPop); }, []);
  const navigate = (next: View) => { setView(next); history.pushState({}, '', `/?view=${next}`); };
  const signIn = () => identity.login({ redirectUri: `${location.origin}/callback` });
  if (!identity.authenticated || identityError) return <div className="sign-in"><div className="entry-nav"><Brand/><span className="eyebrow">LOCAL SIMULATION</span></div><main className="entry-grid"><div><span className="eyebrow">GROCERY FULFILMENT</span><h1>Every movement.<br/><em>Accounted for.</em></h1><p>Follow orders from stock reservation to confirmed equipment movement. See what is running, what is waiting, and what needs attention.</p>{identityError && <div className="notice" role="alert">{identityError}</div>}<button className="primary" onClick={() => identityError ? location.reload() : void signIn()}>{identityError ? 'Retry connection' : 'Sign in to operations'}<Icon kind="arrow"/></button><div className="entry-note">Local identity · Synthetic orders · Simulated equipment</div></div><div className="entry-diagram" aria-label="Workflow: Reserve stock, Coordinate work, Confirm movement"><div className="diagram-heading">THE WORKFLOW<span>01—03</span></div>{[['01', 'Reserve stock', 'Record the order and available quantities.'], ['02', 'Coordinate work', 'Assign a compatible lane and a task owner.'], ['03', 'Confirm movement', 'Consume stock after equipment evidence.']].map(([number, title, description]) => <div className="diagram-step" key={number}><span>{number}</span><div><h2>{title}</h2><p>{description}</p></div></div>)}<div className="diagram-footer">A local modernization lab</div></div></main></div>;
  const all = orders?.items ?? []; const completed = all.filter(order => terminal(order.state)).length; const active = all.length - completed;
  const shortages = all.reduce((total, order) => total + order.lines.reduce((sum, line) => sum + line.shortage, 0), 0);
  const blocked = tasks.filter(task => ['BLOCKED', 'RECONCILIATION_REQUIRED'].includes(task.state));
  const username = identity.tokenParsed?.preferred_username ?? 'Local operator';
  const open = (order: Order) => { setSelected(order); setCommand(undefined); setCommandError(undefined); };
  const loadCommand = async (movement: string) => { setCommand(undefined); setCommandError(undefined); try { setCommand(await get<Command>(`${sitePath(site)}/commands/${movement}`)); } catch (failure) { setCommandError(failure instanceof Error ? failure.message : 'No command evidence is available yet.'); } };
  const orderTable = (rows: Order[]) => <div className="table-wrap"><table><thead><tr><th>Order reference</th><th>Store</th><th>Lines</th><th>Units reserved</th><th>State</th><th>Received</th></tr></thead><tbody>{rows.map(order => <tr key={order.id}><td><button className="row-link" onClick={() => open(order)}>{order.externalOrderRef}</button><small>{short(order.id)}</small></td><td>{label(order.storeId)}</td><td>{order.lines.length}</td><td>{order.lines.reduce((sum, line) => sum + line.reserved, 0)}</td><td><Status value={order.state}/></td><td className="muted">{new Date(order.createdAt).toLocaleTimeString()}</td></tr>)}</tbody></table>{!rows.length && <div className="empty"><Icon kind="orders" size={28}/><strong>{loading ? 'Loading orders…' : 'No orders in this view'}</strong><span>Orders appear when the site receives work.</span></div>}</div>;
  return <div className="shell"><a className="skip" href="#main">Skip to content</a><aside className="sidebar"><Brand/><div className="workspace-label">WORKSPACE</div><nav aria-label="Main navigation">{(Object.keys(names) as View[]).map(item => <button key={item} aria-current={view === item ? 'page' : undefined} onClick={() => navigate(item)}><Icon kind={item}/>{names[item]}{item === 'orders' && all.length > 0 && <span className="nav-count">{all.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="local-marker"><i/>Local platform</div><p>Simulated equipment.<br/>Real ownership boundaries.</p><div className="user"><span className="avatar">{String(username).slice(0, 1).toUpperCase()}</span><div><strong>{label(String(username))}</strong><small>{identity.hasRealmRole('supervisor') ? 'Supervisor' : 'Operator'}</small></div><button className="icon-button" aria-label="Sign out" onClick={() => void identity.logout({ redirectUri: location.origin + '/' })}><Icon kind="logout" size={18}/></button></div></div></aside><div className="workspace"><header className="topbar"><div className="breadcrumb">Operations<span>/</span><strong>{names[view]}</strong></div><div className="topbar-right"><label className="site-picker"><span className="sr-only">Active site</span><select value={site} onChange={event => { setSite(event.target.value); setOrders(undefined); setEquipment(undefined); setTasks([]); setCursor(undefined); }} disabled={sites.length < 2}>{sites.map(value => <option key={value}>{value}</option>)}</select></label><span className="simulation">SIMULATION</span></div></header><main id="main"><div className="page-heading"><div><div className="eyebrow">{label(site)} · OUTBOUND OPERATIONS</div><h1>{view === 'overview' ? 'The floor, in focus.' : names[view]}</h1><p>{view === 'overview' ? 'Orders, movement progress and equipment observations in one place.' : view === 'orders' ? 'Inspect reservations, shortages and the evidence behind each movement.' : 'Live lane observations from the equipment adapter.'}</p></div><button className={`secondary ${loading ? 'refreshing' : ''}`} onClick={() => void refresh()} disabled={loading}><Icon kind="refresh" size={17}/>{loading ? 'Refreshing' : 'Refresh'}</button></div>{error && <div className="notice" role="alert"><strong>Some observations are unavailable.</strong> {error} Retained data may be stale.</div>}<div className="observation-line"><span className={`dot ${error ? 'amber' : ''}`}/>{observedAt ? `Last refreshed ${date(observedAt)}` : 'Waiting for the first site observation'}<span>Times shown in {Intl.DateTimeFormat().resolvedOptions().timeZone}</span></div>
    {view === 'overview' && <><section className="metrics" aria-label="Orders on the current page">{[['Orders in view', all.length, 'Current page · up to 25 orders'], ['Active orders', active, 'Awaiting confirmed movements'], ['Finished orders', completed, 'Includes terminal shortages'], ['Unreserved units', shortages, 'Shortages retained on each order']].map(([title, value, description]) => <article className="metric" key={title}><span>{title}</span><strong>{value}</strong><small>{description}</small></article>)}</section><div className="overview-grid"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">MOVEMENT PATH</span><h2>From reservation to staging</h2></div><span className="quiet-tag">Legacy coordinator</span></div><div className="flow">{[['orders', 'Core', 'Stock & reservations'], ['overview', 'Adapter', 'Allocation & command journal'], ['equipment', 'Simulator', 'Physical movement ledger']].map(([icon, title, description], index) => <div className="flow-node" key={title}><span className="flow-icon"><Icon kind={icon}/></span><strong>{title}</strong><span>{description}</span>{index < 2 && <div className="flow-arrow"><Icon kind="arrow" size={17}/></div>}</div>)}</div><div className="panel-foot"><Icon kind="check" size={16}/>Completion is recorded only after confirmed equipment evidence.</div></section><section className="panel attention-panel"><div className="panel-heading"><div><span className="eyebrow">TASKS IN VIEW</span><h2>Needs attention</h2></div><span className="count-badge">{blocked.length}</span></div>{blocked.length ? blocked.slice(0, 4).map(task => <div className="attention-item" key={task.id}><Status value={task.state}/><p>{label(task.zoneId)} · {short(task.movementId)}</p><small>{task.lastError ? label(task.lastError) : 'Awaiting the next observation'}</small></div>) : <div className="calm-state"><span><Icon kind="check" size={24}/></span><strong>No blocked tasks in this view</strong><p>Blocked or uncertain movements will appear here with their recorded reason.</p></div>}</section></div><section className="panel order-panel"><div className="panel-heading"><div><span className="eyebrow">CURRENT ORDER PAGE</span><h2>Order activity</h2></div><button className="text-button" onClick={() => navigate('orders')}>View orders<Icon kind="arrow" size={16}/></button></div>{orderTable(all.slice(0, 6))}</section></>}
    {view === 'orders' && <section className="panel order-panel"><div className="panel-heading"><h2>Order register</h2><span className="muted">{all.length} orders on this page</span></div>{orderTable(all)}<div className="pagination"><button className="secondary" disabled={!cursor} onClick={() => setCursor(undefined)}>First page</button><button className="secondary" disabled={!orders?.nextCursor} onClick={() => setCursor(orders?.nextCursor ?? undefined)}>Next page<Icon kind="arrow" size={16}/></button></div></section>}
    {view === 'equipment' && <><div className="equipment-summary"><Status value={!equipment?.observedAt ? 'AWAITING_OBSERVATION' : equipment.stale || equipment.worldMismatch ? 'RECONCILIATION_REQUIRED' : 'READY'}/><span>Observed {date(equipment?.observedAt)}</span><span>World {equipment?.worldId ? short(equipment.worldId) : 'not observed'}</span></div>{equipment?.worldMismatch && <div className="notice" role="alert">The simulator world or retained history differs. Dispatch requires reconciliation.</div>}<div className="lane-grid">{(equipment?.lanes ?? []).map(lane => <article className={`panel lane ${lane.blocked ? 'lane-blocked' : ''}`} key={lane.laneId}><div className="lane-top"><span className="flow-icon"><Icon kind="equipment"/></span><Status value={equipment?.stale || equipment?.worldMismatch ? 'STALE_OBSERVATION' : lane.blocked ? 'BLOCKED' : 'READY'}/></div><span className="eyebrow">{label(lane.zoneId)}</span><h2>{label(lane.laneId)}</h2><div className="lane-graphic" aria-hidden="true"><i/><i/><i/><i/><i/></div><div className="panel-foot">{lane.blocked ? 'Waiting for the lane to become available' : 'Available for compatible movements'}<small>Observation version {lane.version}</small></div></article>)}</div>{!equipment?.lanes.length && <div className="empty">No equipment observations are available.</div>}</>}
    <footer className="page-footer"><span>Cutover · Local modernization lab</span><span>Stock remains owned by the core.</span></footer></main></div>
    <dialog ref={dialog} onClose={() => setSelected(undefined)} aria-labelledby="order-detail-title"><div className="dialog-header"><div><span className="eyebrow">ORDER TRACE</span><h2 id="order-detail-title">{selected?.externalOrderRef}</h2></div><button className="icon-button" aria-label="Close order details" onClick={() => dialog.current?.close()}><Icon kind="close"/></button></div>{selected && <div className="dialog-body"><div className="detail-summary"><Status value={selected.state}/><span>{label(selected.storeId)}</span><span>{date(selected.createdAt)}</span></div><h3>Reservation breakdown</h3><table><thead><tr><th>Product</th><th>Requested</th><th>Reserved</th><th>Short</th></tr></thead><tbody>{selected.lines.map(line => <tr key={line.sku}><td>{line.sku}</td><td>{line.requested}</td><td>{line.reserved}</td><td className={line.shortage ? 'shortage' : ''}>{line.shortage}</td></tr>)}</tbody></table><h3>Logical movements</h3><div className="movement-list">{selected.movements.map(movement => <button key={movement.movementId} onClick={() => void loadCommand(movement.movementId)}><div><strong>{label(movement.movement.zoneId)} · {movement.movement.quantity} units</strong><small>{short(movement.movementId)} · {movement.movement.destination}</small></div><Status value={movement.state}/><Icon kind="arrow" size={16}/></button>)}</div>{commandError && <div className="notice" role="status">{commandError}</div>}{command && <section className="command-proof"><span className="eyebrow">ADAPTER COMMAND JOURNAL</span><h3>{command.state === 'COMPLETED' ? 'Verified completion' : 'Recorded movement state'}</h3><dl><div><dt>State</dt><dd><Status value={command.state}/></dd></div><div><dt>Dispatch owner</dt><dd>{command.owner} · epoch {command.epoch}</dd></div><div><dt>Transport attempts</dt><dd>{command.attempts}</dd></div><div><dt>Physical execution sequence</dt><dd>{command.evidence?.executionSequence ?? 'Not yet confirmed'}</dd></div><div><dt>Completed</dt><dd>{date(command.completedAt)}</dd></div></dl>{command.lastError && <p>{label(command.lastError)}</p>}</section>}<p className="detail-id">Order {selected.id}</p></div>}</dialog></div>;
}
